package extralock

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"vulns-news/src/domain"
)

const pubFixture = `# Generated by pub
packages:
  async:
    dependency: transitive
    description:
      name: async
      sha256: "0123456789abcdef"
      url: "https://pub.dev"
    source: hosted
    version: "2.11.0"
  collection:
    dependency: "direct main"
    description:
      name: collection
      url: "https://pub.dev/"
    source: hosted
    version: "1.18.0"
  test:
    dependency: "direct dev"
    description: {name: test, url: "https://pub.dev"}
    source: hosted
    version: "1.25.2"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  private:
    dependency: "direct main"
    description: {name: private, url: "https://packages.example.com"}
    source: hosted
    version: "1.0.0"
sdks:
  dart: ">=3.2.0 <4.0.0"
`
const denoFixture = `{
 "version":"4",
 "specifiers":{"npm:@scope/tool@^2":"2.1.0","jsr:@std/path@^1":"1.0.8"},
 "npm":{
   "@scope/tool@2.1.0":{"integrity":"sha512-abcdef==","dependencies":["chalk"]},
   "chalk@5.3.0":{"integrity":"sha512-fedcba=="},
   "my_tool@1.2.3_react@18.2.0":{"integrity":"sha512-peer=="}
 },
 "jsr":{"@std/path@1.0.8":{"integrity":"abcdef0123456789","dependencies":["jsr:@std/assert"]}},
 "remote":{"https://deno.land/std/mod.ts":"abcdef"},
 "workspace":{"dependencies":["npm:@scope/tool@^2","jsr:@std/path@^1"]}
}`
const configFixture = `<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Newtonsoft.Json" version="13.0.3" targetFramework="net48" />
  <package id="Microsoft.Bcl.AsyncInterfaces" version="8.0.0" targetFramework="net48" developmentDependency="true" />
</packages>`
const assetsFixture = `{
 "version":3,
 "targets":{"net8.0":{"Newtonsoft.Json/13.0.3":{"type":"package"},"Local.Library/1.0.0":{"type":"project"}}},
 "libraries":{
  "Newtonsoft.Json/13.0.3":{"sha512":"abcdef==","type":"package","path":"newtonsoft.json/13.0.3","files":["lib/net6.0/Newtonsoft.Json.dll"]},
  "Local.Library/1.0.0":{"type":"project","path":"../Local.Library/Local.Library.csproj","msbuildProject":"../Local.Library/Local.Library.csproj"}
 },
 "projectFileDependencyGroups":{"net8.0":["Newtonsoft.Json >= 13.0.3","Local.Library >= 1.0.0"]},
 "packageFolders":{"/home/user/.nuget/packages/":{}},
 "project":{"restore":{"sources":{"https://api.nuget.org/v3/index.json":{}}}}
}`
const renvFixture = `{
 "R":{"Version":"4.3.2","Repositories":[{"Name":"CRAN","URL":"https://cloud.r-project.org"}]},
 "Packages":{
  "MASS":{"Package":"MASS","Version":"7.3-60","Source":"Repository","Repository":"CRAN","Hash":"abc","Requirements":["R","grDevices"]},
  "renv":{"Package":"renv","Version":"1.0.7","Source":"Repository","Repository":"CRAN","Hash":"def"},
  "BiocGenerics":{"Package":"BiocGenerics","Version":"0.48.1","Source":"Bioconductor","Repository":"Bioconductor"},
  "custom":{"Package":"custom","Version":"1.0.0","Source":"GitHub","RemoteHost":"api.github.com","RemoteRepo":"custom"}
 }
}`

func put(t *testing.T, root, name, content string) {
	t.Helper()
	file := filepath.Join(root, filepath.FromSlash(name))
	if err := os.MkdirAll(filepath.Dir(file), 0700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(file, []byte(content), 0600); err != nil {
		t.Fatal(err)
	}
}
func TestRealisticInventory(t *testing.T) {
	root := t.TempDir()
	fixtures := map[string]string{"dart/pubspec.lock": pubFixture, "deno/deno.lock": denoFixture, "dotnet/packages.config": configFixture, "dotnet/obj/project.assets.json": assetsFixture, "r/renv.lock": renvFixture}
	for file, data := range fixtures {
		put(t, root, file, data)
	}
	f, err := Profile(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(f.Components) != 12 {
		t.Fatalf("got %d components: %+v", len(f.Components), f.Components)
	}
	wantEcos := []string{"CRAN", "JSR", "NuGet", "Pub", "npm"}
	var ecos []string
	for _, e := range f.Ecosystems {
		ecos = append(ecos, e.Name)
	}
	if !reflect.DeepEqual(ecos, wantEcos) {
		t.Fatalf("ecosystems: %v", ecos)
	}
	byName := map[string][]domain.Component{}
	ids := map[string]bool{}
	for _, c := range f.Components {
		if c.ID == "" || ids[c.ID] {
			t.Fatalf("bad ID: %+v", c)
		}
		ids[c.ID] = true
		if _, ok := fixtures[c.SourcePath]; !ok {
			t.Fatalf("invalid source path: %+v", c)
		}
		if strings.Contains(c.PURL, "@") || strings.Contains(c.PURL, c.Version) {
			t.Fatalf("versioned PURL: %+v", c)
		}
		byName[c.Name] = append(byName[c.Name], c)
	}
	for name, want := range map[string]string{"@scope/tool": "pkg:npm/%40scope/tool", "@std/path": "pkg:jsr/%40std/path", "MASS": "pkg:cran/MASS", "newtonsoft.json": "pkg:nuget/newtonsoft.json", "collection": "pkg:pub/collection"} {
		if len(byName[name]) == 0 || byName[name][0].PURL != want {
			t.Fatalf("%s: %+v", name, byName[name])
		}
	}
	if byName["@scope/tool"][0].Namespace != "@scope" || byName["@std/path"][0].Namespace != "@std" {
		t.Fatal("namespace lost")
	}
	if byName["my_tool"][0].Version != "1.2.3" {
		t.Fatal("peer context became version")
	}
	if len(byName["newtonsoft.json"]) != 2 {
		t.Fatal("source provenance was deduplicated")
	}
	if !byName["collection"][0].Direct || byName["test"][0].Scope != "development" || byName["async"][0].Direct {
		t.Fatal("pub dependency classification")
	}
	for _, c := range byName["newtonsoft.json"] {
		if c.Direct {
			t.Fatal("NuGet directness is not known")
		}
	}
	for _, e := range f.Ecosystems {
		if e.Name == "NuGet" && (!reflect.DeepEqual(e.Manifests, []string{"dotnet/packages.config"}) || !reflect.DeepEqual(e.Lockfiles, []string{"dotnet/obj/project.assets.json"})) {
			t.Fatalf("NuGet usage: %+v", e)
		}
	}
	if !strings.Contains(strings.Join(f.Warnings, "\n"), "no OSV") {
		t.Fatal("missing CRAN coverage caveat")
	}
	again, err := Profile(root)
	if err != nil || !reflect.DeepEqual(f, again) {
		t.Fatalf("non-deterministic profile: %v", err)
	}
	other := t.TempDir()
	for file, data := range fixtures {
		put(t, other, file, data)
	}
	relocated, err := Profile(other)
	if err != nil || !reflect.DeepEqual(f, relocated) {
		t.Fatalf("absolute root affects inventory: %v", err)
	}
}

func TestDenoVersions(t *testing.T) {
	npm := `{"@a/b@1.2.3":{"integrity":"sha512-abc=="}}`
	for _, tc := range []struct{ version, body string }{
		{"2", `"npm":{"specifiers":{"@a/b@^1":"@a/b@1.2.3"},"packages":` + npm + `}`},
		{"3", `"packages":{"specifiers":{"npm:@a/b@^1":"npm:@a/b@1.2.3"},"npm":` + npm + `}`},
		{"4", `"npm":` + npm}, {"5", `"npm":` + npm},
	} {
		t.Run(tc.version, func(t *testing.T) {
			root := t.TempDir()
			put(t, root, "deno.lock", `{"version":"`+tc.version+`",`+tc.body+`}`)
			f, err := Profile(root)
			if err != nil {
				t.Fatal(err)
			}
			if len(f.Components) != 1 || f.Components[0].Name != "@a/b" {
				t.Fatalf("%+v", f)
			}
		})
	}
}

func TestUnsupportedWarnings(t *testing.T) {
	for _, tc := range []struct{ name, data string }{
		{"deno.lock", `{"version":"99","npm":{"bad":{}}}`},
		{"deno.lock", `{"version":"4","specifiers":{"npm:foo@^1":"1.2.3"}}`},
		{"deno.lock", `{"version":"3","npm":{}}`},
		{"deno.lock", `{"version":"4","npm":{"foo@1.2.3":{}}}`},
		{"deno.lock", `{"version":"5","npm":{"foo@1.2.3":{"integrity":"x","registry":"https://private.example"}}}`},
		{"project.assets.json", `{"version":99,"libraries":{}}`},
		{"project.assets.json", `{"version":3}`},
		{"project.assets.json", `{"version":3,"libraries":{"x/1.0.0":{"type":"reference"}}}`},
		{"pubspec.lock", `unknown: {}`},
		{"pubspec.lock", "packages:\n  foo:\n    source: hosted\n    description: foo\n    version: 1.2.3\n"},
		{"packages.config", `<unknown/>`},
		{"renv.lock", `{"R":{"Version":"4.3.2"}}`},
		{"renv.lock", `{"Packages":{"foo":{"Source":"Repository","Repository":"CRAN","RemoteUrl":"https://evil.example","Package":"foo","Version":"1.2.3"}}}`},
	} {
		t.Run(tc.name+tc.data, func(t *testing.T) {
			root := t.TempDir()
			put(t, root, tc.name, tc.data)
			f, err := Profile(root)
			if err != nil {
				t.Fatal(err)
			}
			if len(f.Components) != 0 || len(f.Warnings) == 0 {
				t.Fatalf("expected warning-only result: %+v", f)
			}
		})
	}
}

func TestInvalidInputNoPartialInventory(t *testing.T) {
	for _, tc := range []struct{ name, data string }{
		{"deno.lock", `{"version":"4"`},
		{"deno.lock", `{"version":"4","version":"5"}`},
		{"deno.lock", `{"version":"4"} {}`},
		{"deno.lock", `null`},
		{"deno.lock", `[]`},
		{"deno.lock", `{"version":4}`},
		{"deno.lock", `{"version":"4","npm":null}`},
		{"deno.lock", `{"version":"4","npm":{"foo@^1.2.3":{"integrity":"x"}}}`},
		{"deno.lock", `{"version":"4","npm":{"@scope/foo@1.2.3":{"integrity":4}}}`},
		{"deno.lock", `{"version":"4","jsr":{"foo@1.2.3":{"integrity":"x"}}}`},
		{"deno.lock", `{"version":"4","npm":{"foo@1.2.3-01":{"integrity":"x"}}}`},
		{"project.assets.json", `{"version":3,"libraries":[]}`},
		{"project.assets.json", `{"version":3,"libraries":{"foo/[1.0,2.0)":{"type":"package"}}}`},
		{"project.assets.json", `{"version":3,"libraries":{"foo/1.0.0":{}}}`},
		{"pubspec.lock", `packages: [`},
		{"pubspec.lock", "packages: {}\npackages: {}\n"},
		{"pubspec.lock", "packages: &p {}\nother: *p\n"},
		{"pubspec.lock", "packages: {}\n---\npackages: {}\n"},
		{"pubspec.lock", "packages:\n  foo:\n    source: hosted\n    description: {name: bar, url: 'https://pub.dev'}\n    dependency: transitive\n    version: 1.0.0\n"},
		{"packages.config", `<packages><package id="Foo" version="1.0.0"></packages>`},
		{"packages.config", `<packages><package id="Foo" version="[1.0,2.0)"/></packages>`},
		{"packages.config", `<packages><package id="Foo"/></packages>`},
		{"packages.config", `<packages/><packages/>`},
		{"packages.config", `<!DOCTYPE packages SYSTEM "file:///etc/passwd"><packages/>`},
		{"packages.config", `<packages><package id="Foo" id="Bar" version="1.0"/></packages>`},
		{"renv.lock", `{"Packages":{"foo":{"Source":"Repository","Repository":"CRAN","Package":"bar","Version":"1.0.0"}}}`},
		{"renv.lock", `{"Packages":{"foo":{"Source":"Repository","Repository":"CRAN","Package":"foo","Version":"latest"}}}`},
	} {
		t.Run(tc.name+tc.data, func(t *testing.T) {
			root := t.TempDir()
			put(t, root, "a/pubspec.lock", pubFixture)
			put(t, root, "z/"+tc.name, tc.data)
			f, err := Profile(root)
			if err == nil {
				t.Fatalf("expected error: %+v", f)
			}
			if !reflect.DeepEqual(f, Fragment{}) {
				t.Fatalf("partial result on error: %+v", f)
			}
			if !strings.Contains(err.Error(), "z/"+tc.name) {
				t.Fatalf("missing error provenance: %v", err)
			}
		})
	}
}

func TestSourceFiltering(t *testing.T) {
	for _, host := range []string{"http://pub.dev", "https://pub.dartlang.org", "https://pub.dev.evil.test", "https://user@pub.dev", "https://pub.dev/private", "https://pub.dev:443", "https://pub.dev?mirror=evil"} {
		t.Run(host, func(t *testing.T) {
			root := t.TempDir()
			data := "packages:\n  foo:\n    source: hosted\n    dependency: transitive\n    description: {name: foo, url: '" + host + "'}\n    version: 1.0.0\n"
			put(t, root, "pubspec.lock", data)
			f, err := Profile(root)
			if err != nil || len(f.Components) != 0 || len(f.Warnings) != 1 {
				t.Fatalf("%+v, %v", f, err)
			}
		})
	}
}
func TestLimits(t *testing.T) {
	for _, kind := range []string{"file", "total", "entries", "depth", "components"} {
		t.Run(kind, func(t *testing.T) {
			root := t.TempDir()
			lim := defaultLimits
			switch kind {
			case "file":
				lim.fileBytes = 16
				put(t, root, "pubspec.lock", pubFixture)
			case "total":
				lim.totalBytes = len(pubFixture) + 1
				put(t, root, "a/pubspec.lock", pubFixture)
				put(t, root, "b/pubspec.lock", pubFixture)
			case "entries":
				lim.entries = 1
				put(t, root, "a", "")
				put(t, root, "b", "")
			case "depth":
				lim.depth = 1
				put(t, root, "a/b/pubspec.lock", pubFixture)
			case "components":
				lim.components = 1
				put(t, root, "pubspec.lock", pubFixture)
			}
			f, err := profile(root, lim)
			if err == nil || !strings.Contains(err.Error(), "limit exceeded") || !reflect.DeepEqual(f, Fragment{}) {
				t.Fatalf("%+v, %v", f, err)
			}
		})
	}
	for _, tc := range []struct{ name, data string }{
		{"deno.lock", strings.Repeat("[", 66) + "0" + strings.Repeat("]", 66)},
		{"pubspec.lock", "x: " + strings.Repeat("[", 66) + "0" + strings.Repeat("]", 66)},
		{"packages.config", strings.Repeat("<x>", 66) + strings.Repeat("</x>", 66)},
	} {
		t.Run(tc.name, func(t *testing.T) {
			root := t.TempDir()
			put(t, root, tc.name, tc.data)
			_, err := Profile(root)
			if err == nil || !strings.Contains(err.Error(), "nesting limit") {
				t.Fatalf("%v", err)
			}
		})
	}
}
func TestSymlinksAndRoot(t *testing.T) {
	root := t.TempDir()
	outside := t.TempDir()
	put(t, outside, "pubspec.lock", "malformed: [")
	put(t, root, "actual/pubspec.lock", pubFixture)
	for _, link := range []struct{ target, name string }{{filepath.Join(outside, "pubspec.lock"), "pubspec.lock"}, {outside, "external"}, {filepath.Join(root, "actual"), "internal"}, {root, "loop"}, {filepath.Join(outside, "missing"), "broken"}} {
		if err := os.Symlink(link.target, filepath.Join(root, link.name)); err != nil {
			t.Skipf("symlink creation unavailable: %v", err)
		}
	}
	f, err := Profile(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(f.Components) != 3 {
		t.Fatalf("symlinks followed: %+v", f)
	}
	if _, err := Profile(filepath.Join(root, "internal")); err == nil {
		t.Fatal("symlink root accepted")
	}
	for _, bad := range []string{"", filepath.Join(root, "missing"), filepath.Join(root, "actual/pubspec.lock")} {
		if _, err := Profile(bad); err == nil {
			t.Fatalf("bad root accepted: %q", bad)
		}
	}
}
func TestIdentityVersionsAndDedup(t *testing.T) {
	root := t.TempDir()
	put(t, root, "deno.lock", `{"version":"5","npm":{"foo@1.0.0":{"integrity":"x"},"foo@2.0.0":{"integrity":"y"},"foo@1.0.0_bar@2.0.0":{"integrity":"x"}}}`)
	f, err := Profile(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(f.Components) != 2 || f.Components[0].PURL != f.Components[1].PURL || f.Components[0].ID == f.Components[1].ID {
		t.Fatalf("%+v", f)
	}
}
